Pkg_list = [
    "Makie"
    "GLMakie"
    "CairoMakie"
    "Meshes"
    "CSV"
    "ColorSchemes"
    "ColorTypes"
    "DSP"
    "DataFrames"
    "DelaunayTriangulation"
    "DifferentialEquations"
    "FFTW"
    "FileIO"
    "FortranFiles"
    "GeometryBasics"
    "GridInterpolations"
    "IJulia"
    "Interpolations"
    "JLD2"
    "JSON"
    "JuliaZH"
    "LaTeXStrings"
    "LegendrePolynomials"
    "MAT"
    "MeshIO"
    "NFFT"
    "OffsetArrays"
    "Optim"
    "ProgressMeter"
    "Quaternions"
    "Rotations"
    "IniFile"
    "DataInterpolations"
    "TimesDates"
    "StatsBase"
    "XLSX"
    "Dates"
    "Markdown"
    "CommonDataFormat"
    "Revise"
    "StaticArrays"
    "QuadGK"
    "LsqFit"
]

ENV["JULIA_PKG_SERVER"] = "https://mirrors.cernet.edu.cn/julia" # 选择镜像
using Pkg
for i in Pkg_list
    @time Pkg.add(i)
end